[package]
name = "genii-log-monitor"
version = "0.1.0"
authors = ["William Zhang <willzhang05@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
