[[containers]]
alias = "HMF"
name = "Houston Main Floor"
install_dir = "/localtmp/luser/HMF"
properties_file = "production.container.log4j.properties"
src_email = "root@hmf.lancium.com"
email_list = ["william.zhang@lancium.com"]
notify_interval = 5
flap_interval = 30
cache_size = 20
enabled = true
